### ISSUE TITLE
Errors on accented characters

### ISSUE THREAD

**Issue by sts10** [sts10/csafe#4]
If any words on the inputted word list have accented characters in them, like `"clichés"`, the program errors out. 

```
thread 'main' panicked at 'byte index 10 is not a char boundary; it is inside 'é' (bytes 9..11) of `mealclichés`', src/lib.rs:56:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think this happens because in `find_unsafe_words` we have `let head = &mashed_word[0..i];` When `i` (the index) is 10, we're the middle of the 'é' character. Another way to frame this is that `"clichés"` is 8 characters rather than 7. 

`assert_ne!("clichés".len(), 7);`

I think this is because the é takes up two `u8`s. Thus iterating through it, character-by-character, is tricky.

Either way, we need a smarter way to work our way through each character of `mashed_word`. We maybe could work with an array of `u16`s from utf16, but I'm not sure how to convert them back to an `str` (maybe we don't need to?).

**Comment by robbystk** [comment]
`str` has a method `is_char_boundary` that will tell you whether the given index is inside a character.  If it is, probably just go to the next `i`.  A character can be up to four bytes, so just working with u16s might not work.

**Comment by sts10** [comment]
Ah, that was a good clue. 

OK here's an attempt, where I opted to use the similar-but-different `get` method: https://github.com/sts10/csafe/blob/accents/src/lib.rs#L47-L55

Need to do more testing of how this code actually handles these types of characters, but existing tests pass and benchmark was basically unaffected.
